const data = {
    products: [
        {
            _id:'1',
            name:'Shingeki No Kyojin manga 1',
            image:'/images/p1.jpg',
            price: 30,
            brand: 'Shingeki',
            rating: 5,
            numReviews: 4567,
            description: 'LA DESESPERADA BATALLA COMIENZA! La raza humana, en antaño dueña del mundo, se enfrenta a la extinción a manos de los titanes, gigantescos monstruos de inteligencia limitada que cazan y devoran personas por diversión. Los supervivientes se hacinan e intentan sobrevivir en una pequeña ciudad… pero algunos ya están hartos: van a atacar',
        },
        {
            _id:'2',
            name:'Shingeki No Kyojin manga 2',
            image:'/images/p2.jpg',
            price: 24,
            brand: 'Shingeki',
            rating: 4.5,
            numReviews: 3226,
            description: 'TRAIDOR! Ya no es un secreto que Eren puede convertirse en titán, pero Armin convence a sus superiores de que no le maten, sino que le utilicen para volver a sellar el muro. Pero el control de Eren sobre su álter ego no es completo y tiende a descontrolarse...',
        },
        {
            _id:'3',
            name:'Shingeki No Kyojin manga 3',
            image:'/images/p3.jpg',
            price: 30,
            brand: 'Shingeki',
            rating: 4,
            numReviews: 7533,
            description: '¡LA HUMANIDAD SE POSPONE! Se desarrolla una táctica arriesgada - llevar a Eren en su forma de titán para intentar reparar la Muralla Rose, recuperando así el territorio humano de los monstruos, por primera vez en un siglo. Pero el autocontrol de Eren está lejos de ser perfecto, y cuando él se descontrola, ni siquiera Armin puede detenerlo! Con la supervivencia de la humanidad en sus enormes hombros, ¿será Eren capaz de volver a sus sentidos, o va a perderse para siempre?!',
        },
        {
            _id:'4',
            name:'Shingeki No Kyojin manga 4',
            image:'/images/p4.jpg',
            price: 28,
            brand: 'Shingeki',
            rating: 5,
            numReviews: 4567,
            description: '¿PUEDES IR A CASA OTRA VEZ? Tras desvelarse que Eren puede convertirse en titán, un consejo decide qué hacer con él, si ejecutarlo para salvar sus almas y a los habitantes de la ciudad, o destinarlo a algún cuerpo del ejército para que ayude a la humanidad.',
        },
        {
            _id:'5',
            name:'Shingeki No Kyojin manga 5',
            image:'/images/p5.jpg',
            price: 26,
            brand: 'Shingeki',
            rating: 4.5,
            numReviews: 7889,
            description: 'TITÁN EN LA CAZA Ahora que la condición de Eren como titán es conocida por todos, el cuerpo de exploración está dispuesto a aprovechar sus capacidades especiales en su lucha contra los terribles titanes. Pero durante una misión aparece una titán hembra que da muestras de una gran inteligencia... ¡muy similar a la de Eren!',
        },
    ],
};
export default data